[Interface]
Address = 10.99.99.2/24
ListenPort = 51820
PrivateKey = <REDACTED>
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -o wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -s 10.20.2.0/24 -o ens5 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -s 10.20.2.0/24 -o ens5 -j MASQUERADE

[Peer]
# wg-east
PublicKey = qspR2qck14MoDjTD5nzBp8sHD1ExYib6E4F4czIv53M=
Endpoint = <REDACTED>:51820
AllowedIPs = 10.99.99.1/32, 10.10.0.0/16
